### ISSUE TITLE
Virtual BAC calculator

### ISSUE THREAD

**Issue by wolftherai** [StonksCo/beer-stonks#42]
Blood alcohol concentration (BAC) calculator.
We need to choose where to implement calculation logic (back or front).

**Comment by AugustasBastys** [comment]
If we are planning to have a panel with beer stocks, then the rest calls will definitely be executed in backend, so I see no issue to calculate BAC in backend.

**Comment by Mikisepic** [comment]
If 2 assignees then let's name branches as `branchname-1` and `branchname-2`
